/**
 * version 1.0
 * contacto --> https://www.linkedin.com/in/david-sanchez-1366b1253/
 * @author David Sánchez
 */

//Paquete al que pertenece la clase
package ClientInterface;



//Importes
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import SharedZone.InterfazImplementacionRMI;
import java.rmi.RemoteException;
import Server.Repostero;
import Server.Horno;
import Server.Empaquetador;
import Server.Almacen;



//CLASE
public class PanelCliente extends javax.swing.JFrame implements Runnable{

    //Atributos
    //Aqui guardaremos la info de todos los reposteros, hornos y empaquetadores
    InterfazImplementacionRMI metodosServer;
    

    //Guardamos las posiciones del mouse en la pantalla
    int xMouse;
    int yMouse;
    
    
    public PanelCliente(InterfazImplementacionRMI _metodosServer) {
        
        //Gestiono el argumento
        this.metodosServer = _metodosServer;
        
        initComponents();
        Image icono = Toolkit.getDefaultToolkit().getImage(PanelCliente.class.getResource("/Fototeca/iconoAplicacionCliente.png"));
        setIconImage(icono);
        
        //Centramos la ventana en la pantalla del usuario que ejecute la aplicacion
        setLocationRelativeTo(null); 
        
        
        //Para que cuando vuelva de minimizarse se coloque bien
        this.addWindowStateListener(e -> {
            if (e.getNewState() == JFrame.NORMAL) {
                setLocationRelativeTo(null); // Centra la ventana en la pantalla
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroung = new javax.swing.JPanel();
        separadorHeader = new javax.swing.JSeparator();
        separadorMenu = new javax.swing.JSeparator();
        header = new javax.swing.JPanel();
        labelCerrar = new javax.swing.JLabel();
        iconoCookienFactory = new javax.swing.JLabel();
        panelCliente = new javax.swing.JLabel();
        iconoMinimizado = new javax.swing.JLabel();
        respostero1 = new javax.swing.JLabel();
        respostero2 = new javax.swing.JLabel();
        respostero3 = new javax.swing.JLabel();
        respostero4 = new javax.swing.JLabel();
        respostero5 = new javax.swing.JLabel();
        horno1 = new javax.swing.JLabel();
        horno2 = new javax.swing.JLabel();
        horno3 = new javax.swing.JLabel();
        menuDerecha = new javax.swing.JPanel();
        logoMedioGrande = new javax.swing.JLabel();
        textoAlmacen = new javax.swing.JLabel();
        textoGalletasAlmacenadas = new javax.swing.JLabel();
        textoGalletasDesperdiciadas1 = new javax.swing.JLabel();
        textoAlmacenGalletasConsumidas = new javax.swing.JTextField();
        textoAlmacenGalletasAlmacenadas = new javax.swing.JTextField();
        textoRepostero1Galletas = new javax.swing.JTextField();
        textoRepostero2Galletas = new javax.swing.JTextField();
        textoRepostero3Galletas = new javax.swing.JTextField();
        textoRepostero4Galletas = new javax.swing.JTextField();
        textoRepostero5Galletas = new javax.swing.JTextField();
        textoRepostero1GalletasDesperdiciadas = new javax.swing.JTextField();
        textoRepostero2GalletasDesperdiciadas = new javax.swing.JTextField();
        textoRepostero3GalletasDesperdiciadas = new javax.swing.JTextField();
        textoRepostero4GalletasDesperdiciadas = new javax.swing.JTextField();
        textoRepostero5GalletasDesperdiciadas = new javax.swing.JTextField();
        textoGalletasDesperdiciadas = new javax.swing.JLabel();
        textoGalletasProducidas = new javax.swing.JLabel();
        separadorColumnaReposteros = new javax.swing.JSeparator();
        textoGalletasHorneadas = new javax.swing.JLabel();
        textoHorneando = new javax.swing.JLabel();
        textoHorno1GalletasHorneadas = new javax.swing.JTextField();
        textoHorno2GalletasHorneadas = new javax.swing.JTextField();
        textoHorno3GalletasHorneadas = new javax.swing.JTextField();
        separadorColumnaHornos = new javax.swing.JSeparator();
        panelControlHorneado1 = new javax.swing.JTextField();
        panelControlHorneado2 = new javax.swing.JTextField();
        panelControlHorneado3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        backgroung.setBackground(new java.awt.Color(204, 204, 204));
        backgroung.setForeground(new java.awt.Color(0, 0, 0));
        backgroung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separadorHeader.setBorder(null);
        separadorHeader.setName(""); // NOI18N
        backgroung.add(separadorHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 1390, 10));

        separadorMenu.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separadorMenu.setBorder(null);
        separadorMenu.setName(""); // NOI18N
        backgroung.add(separadorMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1118, 60, 20, 630));

        header.setBackground(new java.awt.Color(64, 166, 38));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        labelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fototeca/IconoCerrar.png"))); // NOI18N
        labelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCerrarMouseExited(evt);
            }
        });

        iconoCookienFactory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fototeca/logoCookeiFactorySinFondo.png"))); // NOI18N

        panelCliente.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        panelCliente.setForeground(new java.awt.Color(0, 0, 0));
        panelCliente.setText("Panel Cliente");

        iconoMinimizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fototeca/iconoMinimizado.PNG"))); // NOI18N
        iconoMinimizado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoMinimizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoMinimizadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconoMinimizadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconoMinimizadoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(iconoCookienFactory)
                .addGap(441, 441, 441)
                .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 509, Short.MAX_VALUE)
                .addComponent(iconoMinimizado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCerrar)
                .addGap(411, 411, 411))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelCliente))
                    .addComponent(iconoCookienFactory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, headerLayout.createSequentialGroup()
                        .addComponent(labelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(iconoMinimizado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgroung.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 60));

        respostero1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        respostero1.setForeground(new java.awt.Color(0, 0, 0));
        respostero1.setText("Repostero 1");
        backgroung.add(respostero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 130, 40));

        respostero2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        respostero2.setForeground(new java.awt.Color(0, 0, 0));
        respostero2.setText("Repostero 2");
        backgroung.add(respostero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 130, 40));

        respostero3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        respostero3.setForeground(new java.awt.Color(0, 0, 0));
        respostero3.setText("Repostero 3");
        backgroung.add(respostero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 130, 40));

        respostero4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        respostero4.setForeground(new java.awt.Color(0, 0, 0));
        respostero4.setText("Repostero 4");
        backgroung.add(respostero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 130, 40));

        respostero5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        respostero5.setForeground(new java.awt.Color(0, 0, 0));
        respostero5.setText("Repostero 5");
        backgroung.add(respostero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 130, 40));

        horno1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        horno1.setForeground(new java.awt.Color(0, 0, 0));
        horno1.setText("Horno 1");
        backgroung.add(horno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 80, 40));

        horno2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        horno2.setForeground(new java.awt.Color(0, 0, 0));
        horno2.setText("Horno 2");
        backgroung.add(horno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 80, 40));

        horno3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        horno3.setForeground(new java.awt.Color(0, 0, 0));
        horno3.setText("Horno 3");
        backgroung.add(horno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, 80, 40));

        menuDerecha.setBackground(new java.awt.Color(64, 166, 38));

        logoMedioGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fototeca/fotoTamañoMedioCookeiFactorySinFondo.png"))); // NOI18N

        textoAlmacen.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        textoAlmacen.setForeground(new java.awt.Color(0, 0, 0));
        textoAlmacen.setText("Almacen");

        textoGalletasAlmacenadas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textoGalletasAlmacenadas.setForeground(new java.awt.Color(0, 0, 0));
        textoGalletasAlmacenadas.setText("Galletas Almacenadas");

        textoGalletasDesperdiciadas1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textoGalletasDesperdiciadas1.setForeground(new java.awt.Color(0, 0, 0));
        textoGalletasDesperdiciadas1.setText("Galletas Consumidas");

        textoAlmacenGalletasConsumidas.setEditable(false);
        textoAlmacenGalletasConsumidas.setBackground(new java.awt.Color(238, 212, 130));
        textoAlmacenGalletasConsumidas.setForeground(new java.awt.Color(0, 0, 0));
        textoAlmacenGalletasConsumidas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoAlmacenGalletasConsumidas.setFocusable(false);
        textoAlmacenGalletasConsumidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAlmacenGalletasConsumidasActionPerformed(evt);
            }
        });

        textoAlmacenGalletasAlmacenadas.setEditable(false);
        textoAlmacenGalletasAlmacenadas.setBackground(new java.awt.Color(238, 212, 130));
        textoAlmacenGalletasAlmacenadas.setForeground(new java.awt.Color(0, 0, 0));
        textoAlmacenGalletasAlmacenadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoAlmacenGalletasAlmacenadas.setFocusable(false);
        textoAlmacenGalletasAlmacenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAlmacenGalletasAlmacenadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuDerechaLayout = new javax.swing.GroupLayout(menuDerecha);
        menuDerecha.setLayout(menuDerechaLayout);
        menuDerechaLayout.setHorizontalGroup(
            menuDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDerechaLayout.createSequentialGroup()
                .addGroup(menuDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuDerechaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(textoAlmacen))
                    .addGroup(menuDerechaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(menuDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoGalletasAlmacenadas)
                            .addComponent(logoMedioGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuDerechaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(textoAlmacenGalletasAlmacenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuDerechaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(menuDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoGalletasDesperdiciadas1)
                            .addComponent(textoAlmacenGalletasConsumidas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        menuDerechaLayout.setVerticalGroup(
            menuDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDerechaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(textoAlmacen)
                .addGap(28, 28, 28)
                .addComponent(textoGalletasAlmacenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoAlmacenGalletasAlmacenadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(textoGalletasDesperdiciadas1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoAlmacenGalletasConsumidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(logoMedioGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        backgroung.add(menuDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 60, 270, 630));

        textoRepostero1Galletas.setEditable(false);
        textoRepostero1Galletas.setBackground(new java.awt.Color(238, 212, 130));
        textoRepostero1Galletas.setForeground(new java.awt.Color(0, 0, 0));
        textoRepostero1Galletas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoRepostero1Galletas.setFocusable(false);
        textoRepostero1Galletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRepostero1GalletasActionPerformed(evt);
            }
        });
        backgroung.add(textoRepostero1Galletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 200, -1));

        textoRepostero2Galletas.setEditable(false);
        textoRepostero2Galletas.setBackground(new java.awt.Color(238, 212, 130));
        textoRepostero2Galletas.setForeground(new java.awt.Color(0, 0, 0));
        textoRepostero2Galletas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoRepostero2Galletas.setFocusable(false);
        textoRepostero2Galletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRepostero2GalletasActionPerformed(evt);
            }
        });
        backgroung.add(textoRepostero2Galletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 200, -1));

        textoRepostero3Galletas.setEditable(false);
        textoRepostero3Galletas.setBackground(new java.awt.Color(238, 212, 130));
        textoRepostero3Galletas.setForeground(new java.awt.Color(0, 0, 0));
        textoRepostero3Galletas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoRepostero3Galletas.setFocusable(false);
        textoRepostero3Galletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRepostero3GalletasActionPerformed(evt);
            }
        });
        backgroung.add(textoRepostero3Galletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 200, -1));

        textoRepostero4Galletas.setEditable(false);
        textoRepostero4Galletas.setBackground(new java.awt.Color(238, 212, 130));
        textoRepostero4Galletas.setForeground(new java.awt.Color(0, 0, 0));
        textoRepostero4Galletas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoRepostero4Galletas.setFocusable(false);
        textoRepostero4Galletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRepostero4GalletasActionPerformed(evt);
            }
        });
        backgroung.add(textoRepostero4Galletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 200, -1));

        textoRepostero5Galletas.setEditable(false);
        textoRepostero5Galletas.setBackground(new java.awt.Color(238, 212, 130));
        textoRepostero5Galletas.setForeground(new java.awt.Color(0, 0, 0));
        textoRepostero5Galletas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoRepostero5Galletas.setFocusable(false);
        textoRepostero5Galletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRepostero5GalletasActionPerformed(evt);
            }
        });
        backgroung.add(textoRepostero5Galletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 200, -1));

        textoRepostero1GalletasDesperdiciadas.setEditable(false);
        textoRepostero1GalletasDesperdiciadas.setBackground(new java.awt.Color(238, 212, 130));
        textoRepostero1GalletasDesperdiciadas.setForeground(new java.awt.Color(255, 0, 0));
        textoRepostero1GalletasDesperdiciadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoRepostero1GalletasDesperdiciadas.setFocusable(false);
        textoRepostero1GalletasDesperdiciadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRepostero1GalletasDesperdiciadasActionPerformed(evt);
            }
        });
        backgroung.add(textoRepostero1GalletasDesperdiciadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 200, -1));

        textoRepostero2GalletasDesperdiciadas.setEditable(false);
        textoRepostero2GalletasDesperdiciadas.setBackground(new java.awt.Color(238, 212, 130));
        textoRepostero2GalletasDesperdiciadas.setForeground(new java.awt.Color(255, 0, 0));
        textoRepostero2GalletasDesperdiciadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoRepostero2GalletasDesperdiciadas.setFocusable(false);
        textoRepostero2GalletasDesperdiciadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRepostero2GalletasDesperdiciadasActionPerformed(evt);
            }
        });
        backgroung.add(textoRepostero2GalletasDesperdiciadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 200, -1));

        textoRepostero3GalletasDesperdiciadas.setEditable(false);
        textoRepostero3GalletasDesperdiciadas.setBackground(new java.awt.Color(238, 212, 130));
        textoRepostero3GalletasDesperdiciadas.setForeground(new java.awt.Color(255, 0, 0));
        textoRepostero3GalletasDesperdiciadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoRepostero3GalletasDesperdiciadas.setFocusable(false);
        textoRepostero3GalletasDesperdiciadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRepostero3GalletasDesperdiciadasActionPerformed(evt);
            }
        });
        backgroung.add(textoRepostero3GalletasDesperdiciadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 200, -1));

        textoRepostero4GalletasDesperdiciadas.setEditable(false);
        textoRepostero4GalletasDesperdiciadas.setBackground(new java.awt.Color(238, 212, 130));
        textoRepostero4GalletasDesperdiciadas.setForeground(new java.awt.Color(255, 0, 0));
        textoRepostero4GalletasDesperdiciadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoRepostero4GalletasDesperdiciadas.setFocusable(false);
        textoRepostero4GalletasDesperdiciadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRepostero4GalletasDesperdiciadasActionPerformed(evt);
            }
        });
        backgroung.add(textoRepostero4GalletasDesperdiciadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 200, -1));

        textoRepostero5GalletasDesperdiciadas.setEditable(false);
        textoRepostero5GalletasDesperdiciadas.setBackground(new java.awt.Color(238, 212, 130));
        textoRepostero5GalletasDesperdiciadas.setForeground(new java.awt.Color(255, 0, 0));
        textoRepostero5GalletasDesperdiciadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoRepostero5GalletasDesperdiciadas.setFocusable(false);
        textoRepostero5GalletasDesperdiciadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRepostero5GalletasDesperdiciadasActionPerformed(evt);
            }
        });
        backgroung.add(textoRepostero5GalletasDesperdiciadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 200, -1));

        textoGalletasDesperdiciadas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textoGalletasDesperdiciadas.setForeground(new java.awt.Color(0, 0, 0));
        textoGalletasDesperdiciadas.setText("Galletas Desperdiciadas");
        backgroung.add(textoGalletasDesperdiciadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 250, 40));

        textoGalletasProducidas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textoGalletasProducidas.setForeground(new java.awt.Color(0, 0, 0));
        textoGalletasProducidas.setText("Galletas Producidas");
        backgroung.add(textoGalletasProducidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 220, 40));

        separadorColumnaReposteros.setOrientation(javax.swing.SwingConstants.VERTICAL);
        backgroung.add(separadorColumnaReposteros, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 10, 290));

        textoGalletasHorneadas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textoGalletasHorneadas.setForeground(new java.awt.Color(0, 0, 0));
        textoGalletasHorneadas.setText("Galletas Horneadas");
        backgroung.add(textoGalletasHorneadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 250, 40));

        textoHorneando.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textoHorneando.setForeground(new java.awt.Color(0, 0, 0));
        textoHorneando.setText("Horneando");
        backgroung.add(textoHorneando, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 140, 40));

        textoHorno1GalletasHorneadas.setEditable(false);
        textoHorno1GalletasHorneadas.setBackground(new java.awt.Color(238, 212, 130));
        textoHorno1GalletasHorneadas.setForeground(new java.awt.Color(0, 0, 0));
        textoHorno1GalletasHorneadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoHorno1GalletasHorneadas.setFocusable(false);
        textoHorno1GalletasHorneadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoHorno1GalletasHorneadasActionPerformed(evt);
            }
        });
        backgroung.add(textoHorno1GalletasHorneadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 200, -1));

        textoHorno2GalletasHorneadas.setEditable(false);
        textoHorno2GalletasHorneadas.setBackground(new java.awt.Color(238, 212, 130));
        textoHorno2GalletasHorneadas.setForeground(new java.awt.Color(0, 0, 0));
        textoHorno2GalletasHorneadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoHorno2GalletasHorneadas.setFocusable(false);
        textoHorno2GalletasHorneadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoHorno2GalletasHorneadasActionPerformed(evt);
            }
        });
        backgroung.add(textoHorno2GalletasHorneadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 200, -1));

        textoHorno3GalletasHorneadas.setEditable(false);
        textoHorno3GalletasHorneadas.setBackground(new java.awt.Color(238, 212, 130));
        textoHorno3GalletasHorneadas.setForeground(new java.awt.Color(0, 0, 0));
        textoHorno3GalletasHorneadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoHorno3GalletasHorneadas.setFocusable(false);
        textoHorno3GalletasHorneadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoHorno3GalletasHorneadasActionPerformed(evt);
            }
        });
        backgroung.add(textoHorno3GalletasHorneadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, 200, -1));

        separadorColumnaHornos.setOrientation(javax.swing.SwingConstants.VERTICAL);
        backgroung.add(separadorColumnaHornos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 10, 130));

        panelControlHorneado1.setEditable(false);
        panelControlHorneado1.setBackground(new java.awt.Color(255, 255, 255));
        panelControlHorneado1.setForeground(new java.awt.Color(0, 0, 0));
        panelControlHorneado1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelControlHorneado1.setFocusable(false);
        panelControlHorneado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelControlHorneado1ActionPerformed(evt);
            }
        });
        backgroung.add(panelControlHorneado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, 200, -1));

        panelControlHorneado2.setEditable(false);
        panelControlHorneado2.setBackground(new java.awt.Color(255, 255, 255));
        panelControlHorneado2.setForeground(new java.awt.Color(0, 0, 0));
        panelControlHorneado2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelControlHorneado2.setFocusable(false);
        panelControlHorneado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelControlHorneado2ActionPerformed(evt);
            }
        });
        backgroung.add(panelControlHorneado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 200, -1));

        panelControlHorneado3.setEditable(false);
        panelControlHorneado3.setBackground(new java.awt.Color(255, 255, 255));
        panelControlHorneado3.setForeground(new java.awt.Color(0, 0, 0));
        panelControlHorneado3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelControlHorneado3.setFocusable(false);
        panelControlHorneado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelControlHorneado3ActionPerformed(evt);
            }
        });
        backgroung.add(panelControlHorneado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 650, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroung, javax.swing.GroupLayout.PREFERRED_SIZE, 1387, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void labelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelCerrarMouseClicked

    private void labelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseEntered
        labelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fototeca/IconoCerrar2.png")));
    }//GEN-LAST:event_labelCerrarMouseEntered

    private void labelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseExited
        labelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fototeca/IconoCerrar.png")));
    }//GEN-LAST:event_labelCerrarMouseExited

    private void textoRepostero1GalletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRepostero1GalletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRepostero1GalletasActionPerformed

    private void textoRepostero2GalletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRepostero2GalletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRepostero2GalletasActionPerformed

    private void textoRepostero3GalletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRepostero3GalletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRepostero3GalletasActionPerformed

    private void textoRepostero4GalletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRepostero4GalletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRepostero4GalletasActionPerformed

    private void textoRepostero5GalletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRepostero5GalletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRepostero5GalletasActionPerformed

    private void textoRepostero1GalletasDesperdiciadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRepostero1GalletasDesperdiciadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRepostero1GalletasDesperdiciadasActionPerformed

    private void textoRepostero2GalletasDesperdiciadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRepostero2GalletasDesperdiciadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRepostero2GalletasDesperdiciadasActionPerformed

    private void textoRepostero3GalletasDesperdiciadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRepostero3GalletasDesperdiciadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRepostero3GalletasDesperdiciadasActionPerformed

    private void textoRepostero4GalletasDesperdiciadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRepostero4GalletasDesperdiciadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRepostero4GalletasDesperdiciadasActionPerformed

    private void textoRepostero5GalletasDesperdiciadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRepostero5GalletasDesperdiciadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRepostero5GalletasDesperdiciadasActionPerformed

    private void textoAlmacenGalletasAlmacenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAlmacenGalletasAlmacenadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAlmacenGalletasAlmacenadasActionPerformed

    private void textoHorno1GalletasHorneadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoHorno1GalletasHorneadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoHorno1GalletasHorneadasActionPerformed

    private void textoHorno2GalletasHorneadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoHorno2GalletasHorneadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoHorno2GalletasHorneadasActionPerformed

    private void textoAlmacenGalletasConsumidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAlmacenGalletasConsumidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAlmacenGalletasConsumidasActionPerformed

    private void textoHorno3GalletasHorneadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoHorno3GalletasHorneadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoHorno3GalletasHorneadasActionPerformed

    private void iconoMinimizadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoMinimizadoMouseClicked
        Point startLocation = this.getLocation();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int taskbarHeight = Toolkit.getDefaultToolkit().getScreenInsets(this.getGraphicsConfiguration()).bottom;

        Point endLocation = new Point(
            (int) screenSize.getWidth() / 2,
            (int) screenSize.getHeight() - taskbarHeight
        );

        Timer timer = new Timer(10, null);
        timer.addActionListener(new ActionListener() {
            double progress = 0;
            final double step = 0.05;

            @Override
            public void actionPerformed(ActionEvent evt) {
                progress += step;
                if (progress >= 1.0) {
                    timer.stop();
                    setExtendedState(JFrame.ICONIFIED);
                } else {
                    int x = (int) (startLocation.x + progress * (endLocation.x - startLocation.x));
                    int y = (int) (startLocation.y + progress * (endLocation.y - startLocation.y));
                    setLocation(x, y);
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_iconoMinimizadoMouseClicked

    private void iconoMinimizadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoMinimizadoMouseEntered
        iconoMinimizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fototeca/iconoMinimizado2.png")));
    }//GEN-LAST:event_iconoMinimizadoMouseEntered

    private void iconoMinimizadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoMinimizadoMouseExited
        iconoMinimizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fototeca/iconoMinimizado.png")));
    }//GEN-LAST:event_iconoMinimizadoMouseExited

    private void panelControlHorneado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelControlHorneado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelControlHorneado1ActionPerformed

    private void panelControlHorneado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelControlHorneado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelControlHorneado2ActionPerformed

    private void panelControlHorneado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelControlHorneado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelControlHorneado3ActionPerformed

    //METODOS CREADOS A MANO
    public JTextField getTextosReposterosGalletas(int identificadorTexto)
    {
            switch (identificadorTexto) 
            {
                case 0:
                    return textoRepostero1Galletas;
                case 1:
                    return textoRepostero2Galletas;
                case 2:
                    return textoRepostero3Galletas;
                case 3:
                    return textoRepostero4Galletas;
                case 4:
                    return textoRepostero5Galletas;
            }
            
            //Si no entra en ningun case, no devolvemos anda porque no han seleccionado el indice bien
            return null;
    }
    
    public JTextField getTextosReposterosGalletasDesperdiciadas(int identificadorTexto)
    {
            switch (identificadorTexto) 
            {
                case 0:
                    return textoRepostero1GalletasDesperdiciadas;
                case 1:
                    return textoRepostero2GalletasDesperdiciadas;
                case 2:
                    return textoRepostero3GalletasDesperdiciadas;
                case 3:
                    return textoRepostero4GalletasDesperdiciadas;
                case 4:
                    return textoRepostero5GalletasDesperdiciadas;
            }
            
            //Si no entra en ningun case, no devolvemos anda porque no han seleccionado el indice bien
            return null;
    }
    
    
    public JTextField getTextosTotalGalletasHorneadas(int identificadorTexto)
    {
            switch (identificadorTexto) 
            {
                case 0:
                    return textoHorno1GalletasHorneadas;
                case 1:
                    return textoHorno2GalletasHorneadas;
                case 2:
                    return textoHorno3GalletasHorneadas;
            }
            
            //Si no entra en ningun case, no devolvemos anda porque no han seleccionado el indice bien
            return null;
    }
    
    public JTextField getPanelControlHorneado(int identificadorTexto)
    {
            switch (identificadorTexto) 
            {
                case 0:
                    return panelControlHorneado1;
                case 1:
                    return panelControlHorneado2;
                case 2:
                    return panelControlHorneado3;
            }
            
            //Si no entra en ningun case, no devolvemos anda porque no han seleccionado el indice bien
            return null;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroung;
    private javax.swing.JPanel header;
    private javax.swing.JLabel horno1;
    private javax.swing.JLabel horno2;
    private javax.swing.JLabel horno3;
    private javax.swing.JLabel iconoCookienFactory;
    private javax.swing.JLabel iconoMinimizado;
    private javax.swing.JLabel labelCerrar;
    private javax.swing.JLabel logoMedioGrande;
    private javax.swing.JPanel menuDerecha;
    private javax.swing.JLabel panelCliente;
    private javax.swing.JTextField panelControlHorneado1;
    private javax.swing.JTextField panelControlHorneado2;
    private javax.swing.JTextField panelControlHorneado3;
    private javax.swing.JLabel respostero1;
    private javax.swing.JLabel respostero2;
    private javax.swing.JLabel respostero3;
    private javax.swing.JLabel respostero4;
    private javax.swing.JLabel respostero5;
    private javax.swing.JSeparator separadorColumnaHornos;
    private javax.swing.JSeparator separadorColumnaReposteros;
    private javax.swing.JSeparator separadorHeader;
    private javax.swing.JSeparator separadorMenu;
    private javax.swing.JLabel textoAlmacen;
    private javax.swing.JTextField textoAlmacenGalletasAlmacenadas;
    private javax.swing.JTextField textoAlmacenGalletasConsumidas;
    private javax.swing.JLabel textoGalletasAlmacenadas;
    private javax.swing.JLabel textoGalletasDesperdiciadas;
    private javax.swing.JLabel textoGalletasDesperdiciadas1;
    private javax.swing.JLabel textoGalletasHorneadas;
    private javax.swing.JLabel textoGalletasProducidas;
    private javax.swing.JLabel textoHorneando;
    private javax.swing.JTextField textoHorno1GalletasHorneadas;
    private javax.swing.JTextField textoHorno2GalletasHorneadas;
    private javax.swing.JTextField textoHorno3GalletasHorneadas;
    private javax.swing.JTextField textoRepostero1Galletas;
    private javax.swing.JTextField textoRepostero1GalletasDesperdiciadas;
    private javax.swing.JTextField textoRepostero2Galletas;
    private javax.swing.JTextField textoRepostero2GalletasDesperdiciadas;
    private javax.swing.JTextField textoRepostero3Galletas;
    private javax.swing.JTextField textoRepostero3GalletasDesperdiciadas;
    private javax.swing.JTextField textoRepostero4Galletas;
    private javax.swing.JTextField textoRepostero4GalletasDesperdiciadas;
    private javax.swing.JTextField textoRepostero5Galletas;
    private javax.swing.JTextField textoRepostero5GalletasDesperdiciadas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        //la interfaz del cliente estara constantemente refrescando la informacion
                while(true)
                {
                    try
                    {
                        //REPOSTEROS
                        //Checkeamos las galletas totales producidas por cada repostero y lo imprimimos en el JTextField
                        //Checkeamos las galletas totales desperdiciadas por cada repostero y lo imprimimos en el JTextField
                        List<Repostero> listaReposteros = metodosServer.getListaReposteros();
                        for (int indice = 0; indice < listaReposteros.size(); indice++ )
                        {
                            int galletasTotales = listaReposteros.get(indice).getTotalGalletas();
                            int galletasTotalesDesperdiciadas = listaReposteros.get(indice).getTotalGalletasDesperdiciadas();
                            getTextosReposterosGalletas(indice).setText(String.valueOf(galletasTotales));
                            getTextosReposterosGalletasDesperdiciadas(indice).setText(String.valueOf(galletasTotalesDesperdiciadas));
                        }
                        
                        //HORNOS
                        List<Horno> listaHornos = metodosServer.getListaHornos();
                        for (int indice = 0; indice < listaHornos.size(); indice++)
                        {
                            //Checkeamos el total galletas horneadas
                            int totalGalletasHorneadas = listaHornos.get(indice).getTotalGalletasHorneadas();
                            getTextosTotalGalletasHorneadas(indice).setText(String.valueOf(totalGalletasHorneadas));
                            
                            //Check si esta horneando (SI o NO)
                            if(listaHornos.get(indice).getEstaHorneando())
                            {
                                getPanelControlHorneado(indice).setBackground(Color.red);
                            }
                            else
                            {
                                getPanelControlHorneado(indice).setBackground(Color.white);
                            }
                        }
                        
                        
                        //EMPAQUETADORES
                        
                        //ALMACEN
                        
                        
                        //Finalizamos el checkeo para el cliente y esperamos un segundo hasta el siguiente checkeo
                        Thread.sleep(1000);
                    }
                    catch (InterruptedException error)
                    {
                        System.out.println("Se ha producido un error mientras la interfaz del cliente estaba actualizando los datos de la fabrica --> " + error);
                    }
                    catch (RemoteException error)
                    {
                        System.out.println("Se ha producido un error mientras se usaba algun hilo (Reposteros,Hornos,Empaquetadores) del servidor --> " + error);
                    }
                }
    }
}
